name: Vegan Muscle Gain
favicon: null
layout_spectrum: 0.72904
typography_spectrum: 0.27435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefde8'
    - '#8bae9a'
    - '#1e1f23'
    - '#4a4b50'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
