analytics: {}
color:
  brandColors:
    - '#000000'
    - '#fefde8'
    - '#8bae9a'
    - '#1e1f23'
    - '#4a4b50'
  brandStrength: 0.75
  lightness: 0.125
  rhythmicContrast: 0.5
  saturation: 0.5625
cta: {}
layout_spectrum: 0.419764
name: Vegan Muscle Gain
opengraph: {}
purpose: []
typography_spectrum: 0.47587
