name: Vegan Muscle Gain
favicon: null
layout_spectrum: 0.67616
typography_spectrum: 0.47587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefde8'
    - '#8bae9a'
    - '#1e1f23'
    - '#4a4b50'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
